In [1]:
import glob
import pandas as pd
from datetime import datetime, date, timedelta
from plotly import graph_objects as go

In [22]:
Alpha_bt_files = glob.glob(f"/home/cloudcraftz/Office_Projects/10_Fintech/backtest_2.0_dev/HFT-Options-EIS-Global/tradelib/outputs/NF_RSI/RSI_Window_15/2024_NIFTY_RSI_STRADDLE_STRATEGY_window_15_ul_70_ll_15/consolidated_store/*.csv") #new

# Alpha_bt_files = glob.glob(f"/home/cloudcraftz/Office_Projects/10_Fintech/backtest_2.0_dev/HFT-Options-EIS-Global/tradelib/outputs/INT_Straddle/2024_NIFTY_STRADDLE_STRATEGY/consolidated_store/*.csv") #new

Alpha_bt_df_list = [pd.read_csv(i) for i in Alpha_bt_files]

Alpha_df = pd.concat(Alpha_bt_df_list, ignore_index=True)
Alpha_df = Alpha_df[Alpha_df['trade_done']==True]
Alpha_df['Timestamp'] = pd.to_datetime(Alpha_df['timestamp'])
Alpha_df = Alpha_df.set_index("Timestamp")
Alpha_df = Alpha_df.sort_index()

In [23]:
frequency = "D"
Alpha_daily_df = Alpha_df.resample(frequency).last().dropna() #.resample("D").last().dropna()
# Beta_daily_df = Beta_df.resample(frequency).last().dropna()

In [64]:
Alpha_daily_df.head()

,timestamp,trade_done,spot,atm_iv,portfolio_delta,portfolio_gamma,portfolio_vega,portfolio_theta,portfolio_sigma,portfolio_cash,instruments_mtm,portfolio_value,total_contracts
Timestamp,,,,,,,,,,,,,
2024-01-01,2024-01-01 15:30:00,1.0,21731.00,0.123636,0.0,0.0,0.0,0.0,0.0,6603.75,0.0,6603.75,0.0
2024-01-02,2024-01-02 15:30:00,1.0,21654.67,0.126665,0.0,0.0,0.0,0.0,0.0,22027.50,0.0,22027.50,0.0
2024-01-03,2024-01-03 15:30:00,1.0,21508.33,0.120051,0.0,0.0,0.0,0.0,0.0,114163.75,0.0,114163.75,0.0
2024-01-04,2024-01-04 15:30:00,1.0,21659.00,-1.000000,0.0,0.0,0.0,0.0,0.0,114163.75,0.0,114163.75,0.0
2024-01-05,2024-01-05 15:30:00,1.0,21722.00,0.094244,0.0,0.0,0.0,0.0,0.0,157698.75,0.0,157698.75,0.0

In [72]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

strangle_p_value = go.Scatter(x=Alpha_daily_df.index, y=Alpha_daily_df['portfolio_value'], mode='lines', name='portfolio_value', line=dict(color='#4daf4a'))
spot_p_value = go.Scatter(x=Alpha_daily_df.index, y=Alpha_daily_df['spot'], mode='lines', name='spot', line=dict(color='#fd8d3c'))

fig = go.Figure()
fig = make_subplots(specs = [[{"secondary_y": True}]])
fig.add_trace(strangle_p_value)
# fig.add_trace(beta_p_value)

fig.add_trace(spot_p_value, secondary_y = True)

fig.update_layout(
   xaxis = dict(
                title='Date',
            ),
    yaxis = dict(
                title = f'Portfolio Value',
                # tickvals = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            ),

    plot_bgcolor = "white",
    title=f'Portfolio Value | NIFTY Weekly 2024 | RSI Window=15, RSI Upper Limit=70, RSI Lower Limit=15',
)

fig.add_annotation(
                    y=Alpha_daily_df['portfolio_value'][-1],
                    x=Alpha_daily_df.index[-1],
                    text=f"{round(Alpha_daily_df['portfolio_value'][-1]/1000)}K",
                    showarrow=False,
                    xshift=30,
                    yshift=10,
                    bgcolor='#4daf4a',
                    font_color='rgb(255, 255, 255)',
                    font_size=17
                )

fig.add_annotation(
                    y=Alpha_daily_df['spot'][-1],
                    x=Alpha_daily_df.index[-1],
                    text=f"{round(Alpha_daily_df['spot'][-1]/1000)}K",
                    showarrow=False,
                    xshift=30,
                    yshift=10,
                    bgcolor='#fd8d3c',
                    font_color='rgb(255, 255, 255)',
                    font_size=17
                )

fig.update_xaxes(
                mirror=True,
                ticks='outside',
                showline=True,
                linecolor='black',
                gridcolor='white')
 
fig.update_yaxes(
            mirror=True,
            ticks='outside',
            showline=True,
            linecolor='black',
            gridcolor='white')

fig.update_yaxes(title_text = f"spot", secondary_y = True)

# Show the figure
fig.show()

In [33]:
H23_df = pd.read_csv(f"/home/cloudcraftz/Office_Projects/10_Fintech/backtest_2.0_dev/HFT-Options-EIS-Global/tradelib/outputs/NF_RSI/RSI_Window_15/2024_NIFTY_RSI_STRADDLE_STRATEGY_window_15_ul_70_ll_15/backtest/20240603.csv")
H23_df.head()

,timestamp,trade_done,spot,atm_iv,portfolio_delta,portfolio_gamma,portfolio_vega,portfolio_theta,portfolio_sigma,portfolio_cash,instruments_mtm,portfolio_value,total_contracts
0,2024-06-03 09:20:00,False,23173.33,0.363653,0.0,0.0,0.0,0.0,0.0,-432091.25,0.0,-432091.25,0.0
1,2024-06-03 09:20:00,True,23173.33,0.363653,0.0,0.0,0.0,0.0,0.0,-432091.25,0.0,-432091.25,0.0
2,2024-06-03 09:21:00,False,23180.00,0.366146,0.0,0.0,0.0,0.0,0.0,-432091.25,0.0,-432091.25,0.0
3,2024-06-03 09:21:00,True,23180.00,0.366146,0.0,0.0,0.0,0.0,0.0,-432091.25,0.0,-432091.25,0.0
4,2024-06-03 09:22:00,False,23170.67,0.364365,0.0,0.0,0.0,0.0,0.0,-432091.25,0.0,-432091.25,0.0

In [74]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def Comparison(comp_var, date_1):
    date_str = date_1.strftime("%Y%m%d")
    print(date_str)

    # backtest_df = pd.read_csv(f"/home/cloudcraftz/Downloads/SPX_Condor_Mid_2023/object_store/backtest/{date_str}.csv") #old
    # backtest_df = pd.read_csv(f"/home/cloudcraftz/Office_Projects/10_Fintech/future_intraday_22_jul/HFT-Options-EIS-Global/sig_sample/outputs/SPXW/test_condor_1/object_store/backtest/{date_str}.csv") #old
    H23_df = pd.read_csv(f"/home/cloudcraftz/Office_Projects/10_Fintech/backtest_2.0_dev/HFT-Options-EIS-Global/tradelib/outputs/NF_RSI/RSI_Window_15/2024_NIFTY_RSI_STRADDLE_STRATEGY_window_15_ul_70_ll_15/backtest/{date_str}.csv") #new
    # H23_df = pd.read_csv(f"/home/cloudcraftz/Office_Projects/10_Fintech/backtest_2.0_dev/HFT-Options-EIS-Global/tradelib/outputs/INT_Straddle/2024_NIFTY_STRADDLE_STRATEGY/consolidated_store/{date_str}.csv") #new

    H23_df = H23_df[H23_df['trade_done']==True]

    # backtest_df['Timestamp'] = pd.to_datetime(backtest_df['Timestamp'])
    H23_df['Timestamp'] = pd.to_datetime(H23_df['timestamp'])

    # backtest_df = backtest_df.set_index("Timestamp")
    H23_df = H23_df.set_index("Timestamp")

    # backtest_daily_df = backtest_df.sort_index()
    H23_daily_df = H23_df.sort_index()

    # baceline_p_value = go.Scatter(x=backtest_daily_df.index, y=backtest_daily_df["Values"], mode='lines', name="old", line=dict(color='#6baed6'))
    spot_p_value = go.Scatter(x=H23_daily_df.index, y=H23_daily_df['atm_iv'], mode='lines', name='atm iv')
    strangle_p_value = go.Scatter(x=H23_daily_df.index, y=H23_daily_df["portfolio_value"], mode='lines', name='New', line=dict(color='#4daf4a'))

    fig = go.Figure()
    fig = make_subplots(specs = [[{"secondary_y": True}]])

    # fig.add_trace(baceline_p_value)
    fig.add_trace(strangle_p_value)
    fig.add_trace(spot_p_value, secondary_y = True)

    fig.update_layout(
    xaxis = dict(
                    title='Date',
                ),
        yaxis = dict(
                    title = f'Portfolio {comp_var}',
                ),

        plot_bgcolor = "white",
        title=f'Minute wise {comp_var} | NIFTY Weekly {date_1.year} | date {date_1.date()} | RSI Window=15, RSI Upper Limit=70, RSI Lower Limit=15',
    )

    fig.update_xaxes(
                    mirror=True,
                    ticks='outside',
                    showline=True,
                    linecolor='black',
                    gridcolor='white')
    
    fig.update_yaxes(
                mirror=True,
                ticks='outside',
                showline=True,
                linecolor='black',
                gridcolor='white')

    fig.update_yaxes(title_text = f"atm_iv", secondary_y = True)

    fig.show()

In [75]:
comp_var = "Values"
a = datetime(2024, 5, 30)
Comparison(comp_var, a)

20240530

In [76]:
comp_var = "Values"
a = datetime(2024, 5, 31)
Comparison(comp_var, a)

20240531

In [77]:
comp_var = "Values"
a = datetime(2024, 6, 3)
Comparison(comp_var, a)

20240603

In [78]:
comp_var = "Values"
a = datetime(2024, 6, 4)
Comparison(comp_var, a)

20240604

In [62]:
df1 = pd.read_csv("/home/cloudcraftz/Downloads/SPX_0DTE_2024_BBO1_instrument_list(in).csv")
print(df1.groupby('expiry_day')['cost'].sum())
print()
print(df1.groupby('expiry_day')['cost'].sum().sum())

expiry_day
Monday       72.271643
Thursday     76.920186
Tuesday      78.700299
Wednesday    78.256380
Name: cost, dtype: float64

306.14850773999996

In [51]:
df1 = pd.read_csv("/home/cloudcraftz/Downloads/SPX_0DTE_2023_BBO1_instrument_list(in).csv")
print(df1.groupby('expiry_day')['cost'].sum())
print()
print(df1.groupby('expiry_day')['cost'].sum().sum())

expiry_day
Monday       64.128026
Thursday     74.880415
Tuesday      73.514048
Wednesday    75.974104
Name: cost, dtype: float64

288.496592493

In [52]:
df1 = pd.read_csv("/home/cloudcraftz/Downloads/SPX_0DTE_2022_BBO1_instrument_list(in).csv")
print(df1.groupby('expiry_day')['cost'].sum())
print()
print(df1.groupby('expiry_day')['cost'].sum().sum())

expiry_day
Monday       78.936237
Thursday     59.746514
Tuesday      59.084094
Wednesday    94.797525
Name: cost, dtype: float64

292.564370337

In [53]:
df1 = pd.read_csv("/home/cloudcraftz/Downloads/SPX_0DTE_2021_BBO1_instrument_list(in).csv")
print(df1.groupby('expiry_day')['cost'].sum())
print()
print(df1.groupby('expiry_day')['cost'].sum().sum())

expiry_day
Monday       65.253820
Thursday      1.906864
Tuesday       2.763071
Wednesday    70.108062
Name: cost, dtype: float64

140.031817401

In [54]:
df1 = pd.read_csv("/home/cloudcraftz/Downloads/SPX_0DTE_2020_BBO1_instrument_list(in).csv")
print(df1.groupby('expiry_day')['cost'].sum())
print()
print(df1.groupby('expiry_day')['cost'].sum().sum())

expiry_day
Monday       61.553796
Thursday      1.423108
Tuesday       3.360148
Wednesday    66.940605
Name: cost, dtype: float64

133.27765703699998